# vim:set ft=dockerfile:

ARG FFMPEG_REF=c791c746b7441cd5e6dee65714933af0d1cd6c48348366715ee3c0d33a20a98f

FROM linuxserver/ffmpeg@sha256:${FFMPEG_REF}

COPY episodes /episodes
COPY tools/generate-metadata.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
